Allow tabs under the patches/ folder. (#2359)
This fixes failures reported here:
https://github.com/ROCm/TheRock/pull/2338#discussion_r2578046353

```
No-tabs checker..........................................................Failed
- hook id: forbid-tabs
- exit code: 1

Tabs detected in file: patches/amd-mainline/rocm-systems/0002-Revert-hsakmt-bump-vgpr-count-for-gfx1151-1807.patch

Error: Process completed with exit code 1.
```

We won't need https://github.com/ROCm/TheRock/pull/2351 once this is
merged.

Tested that the hook still runs for other directories:
```
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing core/0002-Revert-hsakmt-bump-vgpr-count-for-gfx1151-1807.patch

Check Yaml...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for added large files..............................................Passed
Mixed line ending........................................................Passed
black................................................(no files to check)Skipped
clang-format.........................................(no files to check)Skipped
mdformat.............................................(no files to check)Skipped
No-tabs checker..........................................................Failed
- hook id: forbid-tabs
- exit code: 1

Tabs detected in file: core/0002-Revert-hsakmt-bump-vgpr-count-for-gfx1151-1807.patch
```